export const ADD_BOOKING = 'ADD_BOOKING';
export const DELETE_BOOKING = 'DELETE_BOOKING';
export const BOOKINGS_LOADING = 'BOOKINGS_LOADING';
export const EDIT_BOOKING = 'EDIT_BOOKING';
export const GET_BOOKINGS = 'GET_BOOKINGS';
export const FETCH_BOOKINGS_FAILURE = 'FETCH_BOOKINGS_FAILURE';

